/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/client-go/applyconfiguration/networking/v1alpha1"
)

// ModelBoosterSpecApplyConfiguration represents a declarative configuration of the ModelBoosterSpec type for use
// with apply.
type ModelBoosterSpecApplyConfiguration struct {
	Name                     *string                                          `json:"name,omitempty"`
	Owner                    *string                                          `json:"owner,omitempty"`
	Backend                  *ModelBackendApplyConfiguration                  `json:"backend,omitempty"`
	AutoscalingPolicy        *AutoscalingPolicySpecApplyConfiguration         `json:"autoscalingPolicy,omitempty"`
	CostExpansionRatePercent *int32                                           `json:"costExpansionRatePercent,omitempty"`
	ModelMatch               *networkingv1alpha1.ModelMatchApplyConfiguration `json:"modelMatch,omitempty"`
}

// ModelBoosterSpecApplyConfiguration constructs a declarative configuration of the ModelBoosterSpec type for use with
// apply.
func ModelBoosterSpec() *ModelBoosterSpecApplyConfiguration {
	return &ModelBoosterSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelBoosterSpecApplyConfiguration) WithName(value string) *ModelBoosterSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *ModelBoosterSpecApplyConfiguration) WithOwner(value string) *ModelBoosterSpecApplyConfiguration {
	b.Owner = &value
	return b
}

// WithBackend sets the Backend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backend field is set to the value of the last call.
func (b *ModelBoosterSpecApplyConfiguration) WithBackend(value *ModelBackendApplyConfiguration) *ModelBoosterSpecApplyConfiguration {
	b.Backend = value
	return b
}

// WithAutoscalingPolicy sets the AutoscalingPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoscalingPolicy field is set to the value of the last call.
func (b *ModelBoosterSpecApplyConfiguration) WithAutoscalingPolicy(value *AutoscalingPolicySpecApplyConfiguration) *ModelBoosterSpecApplyConfiguration {
	b.AutoscalingPolicy = value
	return b
}

// WithCostExpansionRatePercent sets the CostExpansionRatePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CostExpansionRatePercent field is set to the value of the last call.
func (b *ModelBoosterSpecApplyConfiguration) WithCostExpansionRatePercent(value int32) *ModelBoosterSpecApplyConfiguration {
	b.CostExpansionRatePercent = &value
	return b
}

// WithModelMatch sets the ModelMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelMatch field is set to the value of the last call.
func (b *ModelBoosterSpecApplyConfiguration) WithModelMatch(value *networkingv1alpha1.ModelMatchApplyConfiguration) *ModelBoosterSpecApplyConfiguration {
	b.ModelMatch = value
	return b
}
