/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
)

// ModelServingSpecApplyConfiguration represents a declarative configuration of the ModelServingSpec type for use
// with apply.
type ModelServingSpecApplyConfiguration struct {
	Replicas        *int32                             `json:"replicas,omitempty"`
	SchedulerName   *string                            `json:"schedulerName,omitempty"`
	Template        *ServingGroupApplyConfiguration    `json:"template,omitempty"`
	RolloutStrategy *RolloutStrategyApplyConfiguration `json:"rolloutStrategy,omitempty"`
	RecoveryPolicy  *workloadv1alpha1.RecoveryPolicy   `json:"recoveryPolicy,omitempty"`
}

// ModelServingSpecApplyConfiguration constructs a declarative configuration of the ModelServingSpec type for use with
// apply.
func ModelServingSpec() *ModelServingSpecApplyConfiguration {
	return &ModelServingSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ModelServingSpecApplyConfiguration) WithReplicas(value int32) *ModelServingSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithSchedulerName sets the SchedulerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulerName field is set to the value of the last call.
func (b *ModelServingSpecApplyConfiguration) WithSchedulerName(value string) *ModelServingSpecApplyConfiguration {
	b.SchedulerName = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ModelServingSpecApplyConfiguration) WithTemplate(value *ServingGroupApplyConfiguration) *ModelServingSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithRolloutStrategy sets the RolloutStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RolloutStrategy field is set to the value of the last call.
func (b *ModelServingSpecApplyConfiguration) WithRolloutStrategy(value *RolloutStrategyApplyConfiguration) *ModelServingSpecApplyConfiguration {
	b.RolloutStrategy = value
	return b
}

// WithRecoveryPolicy sets the RecoveryPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryPolicy field is set to the value of the last call.
func (b *ModelServingSpecApplyConfiguration) WithRecoveryPolicy(value workloadv1alpha1.RecoveryPolicy) *ModelServingSpecApplyConfiguration {
	b.RecoveryPolicy = &value
	return b
}
