/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1beta1 "volcano.sh/apis/pkg/apis/scheduling/v1beta1"
)

// NetworkTopologyApplyConfiguration represents a declarative configuration of the NetworkTopology type for use
// with apply.
type NetworkTopologyApplyConfiguration struct {
	GroupPolicy *v1beta1.NetworkTopologySpec `json:"groupPolicy,omitempty"`
	RolePolicy  *v1beta1.NetworkTopologySpec `json:"rolePolicy,omitempty"`
}

// NetworkTopologyApplyConfiguration constructs a declarative configuration of the NetworkTopology type for use with
// apply.
func NetworkTopology() *NetworkTopologyApplyConfiguration {
	return &NetworkTopologyApplyConfiguration{}
}

// WithGroupPolicy sets the GroupPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupPolicy field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithGroupPolicy(value v1beta1.NetworkTopologySpec) *NetworkTopologyApplyConfiguration {
	b.GroupPolicy = &value
	return b
}

// WithRolePolicy sets the RolePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RolePolicy field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithRolePolicy(value v1beta1.NetworkTopologySpec) *NetworkTopologyApplyConfiguration {
	b.RolePolicy = &value
	return b
}
