/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
	v1 "sigs.k8s.io/gateway-api/apis/v1"
)

// ModelRouteSpecApplyConfiguration represents a declarative configuration of the ModelRouteSpec type for use
// with apply.
type ModelRouteSpecApplyConfiguration struct {
	ModelName    *string                      `json:"modelName,omitempty"`
	LoraAdapters []string                     `json:"loraAdapters,omitempty"`
	ParentRefs   []v1.ParentReference         `json:"parentRefs,omitempty"`
	Rules        []*networkingv1alpha1.Rule   `json:"rules,omitempty"`
	RateLimit    *RateLimitApplyConfiguration `json:"rateLimit,omitempty"`
}

// ModelRouteSpecApplyConfiguration constructs a declarative configuration of the ModelRouteSpec type for use with
// apply.
func ModelRouteSpec() *ModelRouteSpecApplyConfiguration {
	return &ModelRouteSpecApplyConfiguration{}
}

// WithModelName sets the ModelName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelName field is set to the value of the last call.
func (b *ModelRouteSpecApplyConfiguration) WithModelName(value string) *ModelRouteSpecApplyConfiguration {
	b.ModelName = &value
	return b
}

// WithLoraAdapters adds the given value to the LoraAdapters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LoraAdapters field.
func (b *ModelRouteSpecApplyConfiguration) WithLoraAdapters(values ...string) *ModelRouteSpecApplyConfiguration {
	for i := range values {
		b.LoraAdapters = append(b.LoraAdapters, values[i])
	}
	return b
}

// WithParentRefs adds the given value to the ParentRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ParentRefs field.
func (b *ModelRouteSpecApplyConfiguration) WithParentRefs(values ...v1.ParentReference) *ModelRouteSpecApplyConfiguration {
	for i := range values {
		b.ParentRefs = append(b.ParentRefs, values[i])
	}
	return b
}

// WithRules adds the given value to the Rules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Rules field.
func (b *ModelRouteSpecApplyConfiguration) WithRules(values ...**networkingv1alpha1.Rule) *ModelRouteSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRules")
		}
		b.Rules = append(b.Rules, *values[i])
	}
	return b
}

// WithRateLimit sets the RateLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimit field is set to the value of the last call.
func (b *ModelRouteSpecApplyConfiguration) WithRateLimit(value *RateLimitApplyConfiguration) *ModelRouteSpecApplyConfiguration {
	b.RateLimit = value
	return b
}
